### ISSUE TITLE
false hexcode in PinAffinity Setup 

### ISSUE THREAD

**Issue by DerRoland** [mjrgh/PinAffinity#1]
Hello Mike,

I use your great tool to reduce stutter on my VPX-VR set. Thanks for that.

Maybe I found a mistake in your hexcodes for the core settings (you set only 1 core for all other, 7 cores for pinball):

(Downloaded from here: http://mjrnet.org/pinscape/downloads/PinAffinity/PinAffinity64-2018-07-25.zip)

`# DEFAULT ENTRY`
`# "Normal" class -> exclude CPUs 1, 2, 3, allow all others.`
`Normal:FFFFFFFFFFFFFF01`

`# "Pinball" class -> enable CPUs 1, 2, 3`
`# for all non-pinball system tasks.`
`Pinball:FFFFFFFFFFFFFFFE`

It should be:

`# DEFAULT ENTRY`
`# "Normal" class -> exclude Core Nr. 3, 4, 5, allow all others`
`# binary = 1111111111111111111111111111111111111111111111111111111111000111`
`Normal:FFFFFFFFFFFFFFC7`

`# "Pinball" class -> set Core 3, 4, 5`
`# for all pinball system tasks.`
`# binary = 111000`
`Pinball:0000000000000038`

I moved the pinball cores to the last three cores, cause windows started to many threads on the first three.

Sincerly
Roland

edit: core counting changed to your prefer: 0,1,2,3,4,5.

**Comment by mjrgh** [comment]
It's actually correct as it is, although certainly the "factory settings" aren't suitable for every system, which is why there's a config file that lets you change the settings easily, rather than having the settings hard-coded into the program.  The factory settings are set the way they are for the reasons explained in the file.   Perhaps what's not clear there is that many people building gaming PCs intentionally avoid hyperthreaded CPUs, because hyperthreading has some inherently negative qualities for gaming applications, so the 4-core case is assumed to be the most common one and therefore the one to optimize for in the defaults.  In a 4-core setup, you typically want it exactly as shown, with all non-game software partitioned to a single core (#0), and the game software getting the remaining cores (#1, 2, and 3).  For a 6-core non-hyperthreaded CPU, this happens to work out so that non-game software gets three cores (0, 4, 5), and VP still gets 1, 2, and 3, which is still a great arrangement: VP can take excellent advantage of three cores, and beyond that, it's diminishing returns, so we might as well let other software have the remaining cores.  

For hyperthreaded CPUs with 8 or more nominal cores, there are other arrangements that might be more optimal.  Windows assigns core numbering for hyperthreaded CPUs with the virtual pairs paired, so 0-1 is the first physical core with its two virtual threads, 2-3 is the second physical core, etc.  So for a hyperthreaded CPU, you might actually be better off disabling the odd-numbered cores entirely for the cores assigned to pinball software, to reduce the negative impact of hyperthreading on the complementary core's throughput.  For example, you might assign cores 0, 2, and 4 to pinball software, and assign all cores 6 and higher to non-game software, leaving cores 1, 3, and 5 assigned to nothing at all, to minimize other software on those cores.  Software running on core 1 will reduce throughput on core 0, so for gaming purposes, where you care more about the speed of a thread in isolation than about overall throughput, you're better off leaving core 1 idle so that the thread on core 0 runs faster.

At any rate, I'm glad you did some experimenting and found more optimal settings for your machine, but I think the factory settings are correct as they are.

**Comment by DerRoland** [comment]
Hello mjrgh,

thanks for your reply. But you don´t explain the different code:

In PinAffinity64-2018-07-25.zip file AffinityTypes.txt contains this: Pinball:FFFFFFFFFFFFFFFE
From github codepage the file AffinityTypes.txt contain this : Pinball:000000000000000E

First hexcode ...FFFE gives Pinball all cores, except core #0 (-++++++++++++++++++...),
Second hexcode ...000E is correct for all type of cpus (-+++----).

Sidenote: When I set core #1 #2 #3 to pinball (-+++--) and #0 #4 #5 to the rest (+---++) my system run very slowly, many tasks seems to hold tight on core #0. With ---+++ and +++--- the system run way better (6 core non HT cpu I8500). Can´t explain why this happen.

Sincerly
Roland

**Comment by mjrgh** [comment]
Oh, I see... I guess I must have not updated the .zip in a while.  I'll upload a fresh copy.
